name: Trigger another repo
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
              curl -X POST https://api.github.com/repos/naomilev/PRWorkflow/actions/workflows/main.yml/dispatches \
              -H 'Accept: application/vnd.github.v3+json' \
              --header 'Authorization: Bearer ${{ secrets.ACTIONS_KEY }}' \
              --data '{"ref": "${{ github.ref }}"}'
