name: Trigger another repo
on:
  workflow_dispatch:
     inputs:
      prworkflow:
        description: 'Ù‹PR Workflow will be triggered'
        required: true
        default: 'prworkflow'

      prworkflow_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'naomilev'

      prworkflow_repo_github:
        description: 'repo-name'
        required: true
        default: 'PRWorkflow' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/naomilev/PRWorkflow/workflows/main.yml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
